### PR TITLE
Eslint upgrade

### PR DESCRIPTION
**Pull request by mcnuttandrew**

### CODE REVIEW

**Comment by jheer** [comment]
Thanks!!

But before merging: Why does this PR re-add the Color Buddy files? (Did you need to change branches and/or `git pull` before this PR?) Can we remove those from this PR before merging?

**Comment by mcnuttandrew** [comment]
That was a miss add, I filed this just as I was running out the door and misfired 😓 . Clean up tommorow

**Comment by mcnuttandrew** [comment]
Alright i think this wraps up the linting upgrade. Notes
- There's a lot of noise because we had not been applying the lints/prettying very consistently and so this also runs the format command. 
- The way the rules are applied in eslint and the way prettier applies them is slightly conflicting. Rather than sort this out, it seems to simpler to make there be 1 formatting command (yarn lint --fix) and one source of formatting truth (eslint)

**Comment by jheer** [comment]
Thank you!!!

**Pull request merged**
